---
- name: Provide a compatable version of libssl (fedora)
  yum:
    name:
      - openssl1.1
    state: latest 
  when:
    - "ansible_facts['distribution'] in ['Fedora']"
    - "ansible_facts['distribution_major_version'] in ['36','37']"
- name: Provide a compatable version of libssl (fedora)
  yum:
    name:
      - compat-openssl11
    state: latest 
  when:
    - "ansible_facts['distribution'] in ['RedHat','CentOS','Rocky']"
    - "ansible_facts['distribution_major_version'] in ['8','9']"
- name: Add Dotnet 6 so the agent can communicate properly
  yum:
    name: dotnet-sdk-6.0
    state: latest
  when:
    - "ansible_facts['distribution'] in ['Fedora']"
    - "ansible_facts['distribution_major_version'] in ['36','37']"
- name: Ensure the externals symlink cron job is in place for podman
  ansible.builtin.copy:
    src: files/fixexternalsymboliclinkonupgrade.sh
    dest: /usr/local/bin/fixexternalsymboliclinkonupgrade.sh
    mode: 0755
- name: Ensure cronie is installed
  ansible.builtin.yum:
    name: cronie
    state: present
- name: Setup the cron job to run every 5 minutes
  ansible.builtin.cron:
    name: "Fix externals symbolic links on GitHub action agent upgrade"
    minute: "*/5"
    user: root
    job: "/usr/local/bin/fixexternalsymboliclinkonupgrade.sh"
    cron_file: fixexternalsymboliclinkonupgrade
- name: Populate service facts
  ansible.builtin.service_facts:
- name: Match services running from that folder 
  shell: |
    cat $(systemctl show -P FragmentPath {{ svc }}) | grep ExecStart | cut -f 2 -d '=' | head -n 1 | xargs dirname
  loop: "{{ ansible_facts.services.keys() | select('search','^actions.runner') | list }}"
  loop_control:
    loop_var: svc
  register: github_actions_service_home_folders
- debug:
    msg: "{{ github_actions_service_home_folders }}"

- name: Uninstall matching agents 
  include_tasks: pre-remove.yml
  loop: "{{ github_actions_agents | default([]) }}"
  loop_control:
    loop_var: agent
- name: Find the latest release from Github API
  ansible.builtin.uri:
    url: https://api.github.com/repos/actions/runner/releases/latest
    return_content: yes
    headers:
      Accept: "application/vnd.github+json"
  register: latest_release
- set_fact:
    github_actions_agent_release_tag: "{{ (latest_release.content | from_json)['tag_name'] }}"
- debug:
    msg: "{{ github_actions_agent_release_tag }}"
- name: Setup agents 
  include_tasks: setup.yml
  loop: "{{ github_actions_agents | default([]) }}"
  loop_control:
    loop_var: agent
  vars:
    github_actions_agent_version: "{{ github_actions_agent_release_tag | regex_replace('v') }}"


# curl -o actions-runner-linux-x64-2.299.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.299.1/actions-runner-linux-x64-2.299.1.tar.gz